// Generated by Haxe 4.1.1
#include <hxcpp.h>

#ifndef INCLUDED_16d41c6fc5b8bf5d
#define INCLUDED_16d41c6fc5b8bf5d
#include "maglev/MagLev.h"
#endif
#ifndef INCLUDED_869a921fcf5bba54
#define INCLUDED_869a921fcf5bba54
#include "maglev/MagLevAny.h"
#endif
#ifndef INCLUDED_20db69a30a45e926
#define INCLUDED_20db69a30a45e926
#include "maglev/MagLevArray.h"
#endif
#ifndef INCLUDED_d8a74f90a5c0b964
#define INCLUDED_d8a74f90a5c0b964
#include "maglev/MagLevError.h"
#endif
#ifndef INCLUDED_7f9204b932c8d809
#define INCLUDED_7f9204b932c8d809
#include "maglev/MagLevFunction.h"
#endif
#ifndef INCLUDED_65acb6100057af6e
#define INCLUDED_65acb6100057af6e
#include "maglev/MagLevResult.h"
#endif
#ifndef INCLUDED_c859d2752ef86c43
#define INCLUDED_c859d2752ef86c43
#include "maglev/MagLevString.h"
#endif
#ifndef INCLUDED_iptools_IPTools
#include <iptools/IPTools.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_d9ba87492f7b1d8f_11_new,"iptools.IPTools","new",0x197c190c,"iptools.IPTools.new","iptools/IPTools.hx",11,0x22d93725)
HX_LOCAL_STACK_FRAME(_hx_pos_d9ba87492f7b1d8f_19_registerMyMethods,"iptools.IPTools","registerMyMethods",0x66304f2f,"iptools.IPTools.registerMyMethods","iptools/IPTools.hx",19,0x22d93725)
HX_LOCAL_STACK_FRAME(_hx_pos_d9ba87492f7b1d8f_30_registerMyMethods,"iptools.IPTools","registerMyMethods",0x66304f2f,"iptools.IPTools.registerMyMethods","iptools/IPTools.hx",30,0x22d93725)
HX_LOCAL_STACK_FRAME(_hx_pos_d9ba87492f7b1d8f_41_registerMyMethods,"iptools.IPTools","registerMyMethods",0x66304f2f,"iptools.IPTools.registerMyMethods","iptools/IPTools.hx",41,0x22d93725)
HX_LOCAL_STACK_FRAME(_hx_pos_d9ba87492f7b1d8f_52_registerMyMethods,"iptools.IPTools","registerMyMethods",0x66304f2f,"iptools.IPTools.registerMyMethods","iptools/IPTools.hx",52,0x22d93725)
HX_LOCAL_STACK_FRAME(_hx_pos_d9ba87492f7b1d8f_63_registerMyMethods,"iptools.IPTools","registerMyMethods",0x66304f2f,"iptools.IPTools.registerMyMethods","iptools/IPTools.hx",63,0x22d93725)
HX_LOCAL_STACK_FRAME(_hx_pos_d9ba87492f7b1d8f_74_registerMyMethods,"iptools.IPTools","registerMyMethods",0x66304f2f,"iptools.IPTools.registerMyMethods","iptools/IPTools.hx",74,0x22d93725)
HX_LOCAL_STACK_FRAME(_hx_pos_d9ba87492f7b1d8f_85_registerMyMethods,"iptools.IPTools","registerMyMethods",0x66304f2f,"iptools.IPTools.registerMyMethods","iptools/IPTools.hx",85,0x22d93725)
HX_LOCAL_STACK_FRAME(_hx_pos_d9ba87492f7b1d8f_96_registerMyMethods,"iptools.IPTools","registerMyMethods",0x66304f2f,"iptools.IPTools.registerMyMethods","iptools/IPTools.hx",96,0x22d93725)
HX_LOCAL_STACK_FRAME(_hx_pos_d9ba87492f7b1d8f_16_registerMyMethods,"iptools.IPTools","registerMyMethods",0x66304f2f,"iptools.IPTools.registerMyMethods","iptools/IPTools.hx",16,0x22d93725)
namespace iptools{

void IPTools_obj::__construct( ::maglev::MagLev maglev){
            	HX_STACKFRAME(&_hx_pos_d9ba87492f7b1d8f_11_new)
HXLINE(  12)		this->maglev = maglev;
HXLINE(  13)		this->registerMyMethods();
            	}

Dynamic IPTools_obj::__CreateEmpty() { return new IPTools_obj; }

void *IPTools_obj::_hx_vtable = 0;

Dynamic IPTools_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< IPTools_obj > _hx_result = new IPTools_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool IPTools_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x7c6d0b1c;
}

void IPTools_obj::registerMyMethods(){
            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::maglev::MagLev,bus) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_STACKFRAME(&_hx_pos_d9ba87492f7b1d8f_19_registerMyMethods)
HXLINE(  20)			 ::maglev::MagLevArray data = ::maglev::MagLevArray_obj::create();
HXLINE(  21)			data->push(::maglev::MagLevString_obj::fromString(HX_("_not_implemented_",a8,29,87,20)));
HXLINE(  22)			data->push(::maglev::MagLevString_obj::fromString(HX_("IPTools.SubnetMaskToCIDR",12,db,0a,75)));
HXLINE(  23)			data->push(::maglev::MagLevString_obj::fromString(HX_("iptools",d4,b0,74,ea)));
HXLINE(  24)			bus->call(HX_("MindPowered.Telemetry.Send",79,51,dc,d8),data);
HXLINE(  25)			 ::maglev::MagLevError err = ::maglev::MagLevError_obj::create(-20000,HX_("You are trying to use the 'IPTools.SubnetMaskToCIDR' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.",b7,78,76,7f),data);
HXLINE(  26)			 ::maglev::MagLevResult result = ::maglev::MagLevResult_obj::fromError(err);
HXLINE(  27)			return result;
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_1, ::maglev::MagLev,bus) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_STACKFRAME(&_hx_pos_d9ba87492f7b1d8f_30_registerMyMethods)
HXLINE(  31)			 ::maglev::MagLevArray data = ::maglev::MagLevArray_obj::create();
HXLINE(  32)			data->push(::maglev::MagLevString_obj::fromString(HX_("_not_implemented_",a8,29,87,20)));
HXLINE(  33)			data->push(::maglev::MagLevString_obj::fromString(HX_("IPTools.CalcCIDR",e3,19,eb,b8)));
HXLINE(  34)			data->push(::maglev::MagLevString_obj::fromString(HX_("iptools",d4,b0,74,ea)));
HXLINE(  35)			bus->call(HX_("MindPowered.Telemetry.Send",79,51,dc,d8),data);
HXLINE(  36)			 ::maglev::MagLevError err = ::maglev::MagLevError_obj::create(-20000,HX_("You are trying to use the 'IPTools.CalcCIDR' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.",08,23,48,c3),data);
HXLINE(  37)			 ::maglev::MagLevResult result = ::maglev::MagLevResult_obj::fromError(err);
HXLINE(  38)			return result;
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_2, ::maglev::MagLev,bus) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_STACKFRAME(&_hx_pos_d9ba87492f7b1d8f_41_registerMyMethods)
HXLINE(  42)			 ::maglev::MagLevArray data = ::maglev::MagLevArray_obj::create();
HXLINE(  43)			data->push(::maglev::MagLevString_obj::fromString(HX_("_not_implemented_",a8,29,87,20)));
HXLINE(  44)			data->push(::maglev::MagLevString_obj::fromString(HX_("IPTools.IPToDecimal",b5,84,dc,f4)));
HXLINE(  45)			data->push(::maglev::MagLevString_obj::fromString(HX_("iptools",d4,b0,74,ea)));
HXLINE(  46)			bus->call(HX_("MindPowered.Telemetry.Send",79,51,dc,d8),data);
HXLINE(  47)			 ::maglev::MagLevError err = ::maglev::MagLevError_obj::create(-20000,HX_("You are trying to use the 'IPTools.IPToDecimal' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.",0e,80,e7,0d),data);
HXLINE(  48)			 ::maglev::MagLevResult result = ::maglev::MagLevResult_obj::fromError(err);
HXLINE(  49)			return result;
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_3, ::maglev::MagLev,bus) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_STACKFRAME(&_hx_pos_d9ba87492f7b1d8f_52_registerMyMethods)
HXLINE(  53)			 ::maglev::MagLevArray data = ::maglev::MagLevArray_obj::create();
HXLINE(  54)			data->push(::maglev::MagLevString_obj::fromString(HX_("_not_implemented_",a8,29,87,20)));
HXLINE(  55)			data->push(::maglev::MagLevString_obj::fromString(HX_("IPTools.IP4FromDecimal",54,55,5c,4f)));
HXLINE(  56)			data->push(::maglev::MagLevString_obj::fromString(HX_("iptools",d4,b0,74,ea)));
HXLINE(  57)			bus->call(HX_("MindPowered.Telemetry.Send",79,51,dc,d8),data);
HXLINE(  58)			 ::maglev::MagLevError err = ::maglev::MagLevError_obj::create(-20000,HX_("You are trying to use the 'IPTools.IP4FromDecimal' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.",79,e8,26,01),data);
HXLINE(  59)			 ::maglev::MagLevResult result = ::maglev::MagLevResult_obj::fromError(err);
HXLINE(  60)			return result;
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_4, ::maglev::MagLev,bus) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_STACKFRAME(&_hx_pos_d9ba87492f7b1d8f_63_registerMyMethods)
HXLINE(  64)			 ::maglev::MagLevArray data = ::maglev::MagLevArray_obj::create();
HXLINE(  65)			data->push(::maglev::MagLevString_obj::fromString(HX_("_not_implemented_",a8,29,87,20)));
HXLINE(  66)			data->push(::maglev::MagLevString_obj::fromString(HX_("IPTools.IP6FromDecimal",92,30,db,d2)));
HXLINE(  67)			data->push(::maglev::MagLevString_obj::fromString(HX_("iptools",d4,b0,74,ea)));
HXLINE(  68)			bus->call(HX_("MindPowered.Telemetry.Send",79,51,dc,d8),data);
HXLINE(  69)			 ::maglev::MagLevError err = ::maglev::MagLevError_obj::create(-20000,HX_("You are trying to use the 'IPTools.IP6FromDecimal' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.",b7,d0,f5,c7),data);
HXLINE(  70)			 ::maglev::MagLevResult result = ::maglev::MagLevResult_obj::fromError(err);
HXLINE(  71)			return result;
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_5, ::maglev::MagLev,bus) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_STACKFRAME(&_hx_pos_d9ba87492f7b1d8f_74_registerMyMethods)
HXLINE(  75)			 ::maglev::MagLevArray data = ::maglev::MagLevArray_obj::create();
HXLINE(  76)			data->push(::maglev::MagLevString_obj::fromString(HX_("_not_implemented_",a8,29,87,20)));
HXLINE(  77)			data->push(::maglev::MagLevString_obj::fromString(HX_("IPTools.IPv4ToIPv6",a1,37,26,e7)));
HXLINE(  78)			data->push(::maglev::MagLevString_obj::fromString(HX_("iptools",d4,b0,74,ea)));
HXLINE(  79)			bus->call(HX_("MindPowered.Telemetry.Send",79,51,dc,d8),data);
HXLINE(  80)			 ::maglev::MagLevError err = ::maglev::MagLevError_obj::create(-20000,HX_("You are trying to use the 'IPTools.IPv4ToIPv6' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.",46,2b,19,df),data);
HXLINE(  81)			 ::maglev::MagLevResult result = ::maglev::MagLevResult_obj::fromError(err);
HXLINE(  82)			return result;
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_6, ::maglev::MagLev,bus) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_STACKFRAME(&_hx_pos_d9ba87492f7b1d8f_85_registerMyMethods)
HXLINE(  86)			 ::maglev::MagLevArray data = ::maglev::MagLevArray_obj::create();
HXLINE(  87)			data->push(::maglev::MagLevString_obj::fromString(HX_("_not_implemented_",a8,29,87,20)));
HXLINE(  88)			data->push(::maglev::MagLevString_obj::fromString(HX_("IPTools.ExpandIPv6",9b,f3,aa,e3)));
HXLINE(  89)			data->push(::maglev::MagLevString_obj::fromString(HX_("iptools",d4,b0,74,ea)));
HXLINE(  90)			bus->call(HX_("MindPowered.Telemetry.Send",79,51,dc,d8),data);
HXLINE(  91)			 ::maglev::MagLevError err = ::maglev::MagLevError_obj::create(-20000,HX_("You are trying to use the 'IPTools.ExpandIPv6' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.",40,6e,37,9e),data);
HXLINE(  92)			 ::maglev::MagLevResult result = ::maglev::MagLevResult_obj::fromError(err);
HXLINE(  93)			return result;
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_7, ::maglev::MagLev,bus) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_STACKFRAME(&_hx_pos_d9ba87492f7b1d8f_96_registerMyMethods)
HXLINE(  97)			 ::maglev::MagLevArray data = ::maglev::MagLevArray_obj::create();
HXLINE(  98)			data->push(::maglev::MagLevString_obj::fromString(HX_("_not_implemented_",a8,29,87,20)));
HXLINE(  99)			data->push(::maglev::MagLevString_obj::fromString(HX_("IPTools.CompressIPv6",63,ab,b0,4d)));
HXLINE( 100)			data->push(::maglev::MagLevString_obj::fromString(HX_("iptools",d4,b0,74,ea)));
HXLINE( 101)			bus->call(HX_("MindPowered.Telemetry.Send",79,51,dc,d8),data);
HXLINE( 102)			 ::maglev::MagLevError err = ::maglev::MagLevError_obj::create(-20000,HX_("You are trying to use the 'IPTools.CompressIPv6' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.",88,8f,a2,25),data);
HXLINE( 103)			 ::maglev::MagLevResult result = ::maglev::MagLevResult_obj::fromError(err);
HXLINE( 104)			return result;
            		}
            		HX_END_LOCAL_FUNC1(return)

            	HX_STACKFRAME(&_hx_pos_d9ba87492f7b1d8f_16_registerMyMethods)
HXLINE(  17)		 ::maglev::MagLev bus = this->maglev;
HXLINE(  19)		 ::maglev::MagLev _hx_tmp = this->maglev;
HXDLIN(  19)		_hx_tmp->_hx_register(HX_("IPTools.SubnetMaskToCIDR",12,db,0a,75),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_0(bus))));
HXLINE(  30)		 ::maglev::MagLev _hx_tmp1 = this->maglev;
HXDLIN(  30)		_hx_tmp1->_hx_register(HX_("IPTools.CalcCIDR",e3,19,eb,b8),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_1(bus))));
HXLINE(  41)		 ::maglev::MagLev _hx_tmp2 = this->maglev;
HXDLIN(  41)		_hx_tmp2->_hx_register(HX_("IPTools.IPToDecimal",b5,84,dc,f4),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_2(bus))));
HXLINE(  52)		 ::maglev::MagLev _hx_tmp3 = this->maglev;
HXDLIN(  52)		_hx_tmp3->_hx_register(HX_("IPTools.IP4FromDecimal",54,55,5c,4f),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_3(bus))));
HXLINE(  63)		 ::maglev::MagLev _hx_tmp4 = this->maglev;
HXDLIN(  63)		_hx_tmp4->_hx_register(HX_("IPTools.IP6FromDecimal",92,30,db,d2),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_4(bus))));
HXLINE(  74)		 ::maglev::MagLev _hx_tmp5 = this->maglev;
HXDLIN(  74)		_hx_tmp5->_hx_register(HX_("IPTools.IPv4ToIPv6",a1,37,26,e7),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_5(bus))));
HXLINE(  85)		 ::maglev::MagLev _hx_tmp6 = this->maglev;
HXDLIN(  85)		_hx_tmp6->_hx_register(HX_("IPTools.ExpandIPv6",9b,f3,aa,e3),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_6(bus))));
HXLINE(  96)		 ::maglev::MagLev _hx_tmp7 = this->maglev;
HXDLIN(  96)		_hx_tmp7->_hx_register(HX_("IPTools.CompressIPv6",63,ab,b0,4d),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_7(bus))));
            	}


HX_DEFINE_DYNAMIC_FUNC0(IPTools_obj,registerMyMethods,(void))


::hx::ObjectPtr< IPTools_obj > IPTools_obj::__new( ::maglev::MagLev maglev) {
	::hx::ObjectPtr< IPTools_obj > __this = new IPTools_obj();
	__this->__construct(maglev);
	return __this;
}

::hx::ObjectPtr< IPTools_obj > IPTools_obj::__alloc(::hx::Ctx *_hx_ctx, ::maglev::MagLev maglev) {
	IPTools_obj *__this = (IPTools_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(IPTools_obj), true, "iptools.IPTools"));
	*(void **)__this = IPTools_obj::_hx_vtable;
	__this->__construct(maglev);
	return __this;
}

IPTools_obj::IPTools_obj()
{
}

void IPTools_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(IPTools);
	HX_MARK_MEMBER_NAME(maglev,"maglev");
	HX_MARK_END_CLASS();
}

void IPTools_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(maglev,"maglev");
}

::hx::Val IPTools_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 6:
		if (HX_FIELD_EQ(inName,"maglev") ) { return ::hx::Val( maglev ); }
		break;
	case 17:
		if (HX_FIELD_EQ(inName,"registerMyMethods") ) { return ::hx::Val( registerMyMethods_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val IPTools_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 6:
		if (HX_FIELD_EQ(inName,"maglev") ) { maglev=inValue.Cast<  ::maglev::MagLev >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void IPTools_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("maglev",2a,df,2b,b3));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo IPTools_obj_sMemberStorageInfo[] = {
	{::hx::fsUnknown /*  ::maglev::MagLev */ ,(int)offsetof(IPTools_obj,maglev),HX_("maglev",2a,df,2b,b3)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *IPTools_obj_sStaticStorageInfo = 0;
#endif

static ::String IPTools_obj_sMemberFields[] = {
	HX_("maglev",2a,df,2b,b3),
	HX_("registerMyMethods",83,b1,0a,b9),
	::String(null()) };

::hx::Class IPTools_obj::__mClass;

void IPTools_obj::__register()
{
	IPTools_obj _hx_dummy;
	IPTools_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("iptools.IPTools",1a,e3,27,ed);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(IPTools_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< IPTools_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = IPTools_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = IPTools_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace iptools
